### ISSUE TITLE
[BUG] Duplicate messages in `say_team` when we have more than 1 player on the same team

### ISSUE THREAD

**Issue by crashzk** [schwarper/cs2-tags#4]
![image](https://github.com/schwarper/cs2-tags/assets/32937653/16e10cbe-b890-4352-95ed-c2d487124ea2)

Checking error logs found nothing.

To play it is simple, configure the TAGS and have more than one player on the same team. In my case I configured it with Admin Groups.

**Comment by schwarper** [comment]
Fixed, https://github.com/schwarper/cs2-tags/commit/dd2057dc34e35137d59d1054cd1bd8b8dbd0038e
