### ISSUE TITLE
Gag system is not working. 

### ISSUE THREAD

**Issue by MickaNoob** [schwarper/cs2-tags#7]
Hello, 

I have detected a problem. The gag system is not working, after silencing / gag a person, he can still write in the chat.

When I deactivate the tags, the person can no longer write.

Have a nice day!

**Comment by schwarper** [comment]
> Hello,
> 
> I have detected a problem. The gag system is not working, after silencing / gag a person, he can still write in the chat.
> 
> When I deactivate the tags, the person can no longer write.
> 
> Have a nice day!

Which admin plugin do you use?

**Comment by MickaNoob** [comment]
I use this plugins

https://github.com/CSSPanel/Plugin
